theme: jekyll-theme-cayman
title: Gemstone.Communication
description: GPA Gemstone Communication Library
github:
  repository_name: gemstone/communication
  owner_url: https://www.gridprotectionalliance.org
  owner_name: Grid Protection Alliance
plugins:
  - jemoji